### PR TITLE
Ui fix userlist

### PR DESCRIPTION
**Pull request by ace0625**
- UI changes on Userlist and User profile

### CODE REVIEW

**Comment by MechanicKim** [comment]
I think this PR is like #112 
#112 need to be passed first! Right?

**Comment by ace0625** [comment]
Yes!

**Comment by MechanicKim** [comment]
The Issue is like #112 .
So, I have no comment anymore!

**Comment by MechanicKim** [comment]
Good! LGTM

[Approved with PullApprove](https://pullapprove.com/sv-bootcamp/bridgeme-client/pull-request/115/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=sv-bootcamp/bridgeme-client)

**Pull request merged**
