### PR TITLE
Import `gifted-chat` library. ready for modify.

### PR DESCRIPTION
**Pull request by lyw0149**
SendBird intergration will be following.

### CODE REVIEW

**Comment by ochanje210** [comment]
could you briefly add your words on why you decided to import the whole library separately?

**Comment by ochanje210** [comment]
please remove unnecessary files

**Comment by lyw0149** [comment]
@ochanje210 Because `react-native-gifted-chat` lib doesn't support UI&Logic customizing. So we should modify this lib directly. This PR will be using as comparing following PR.

**Comment by ace0625** [comment]
LGTM

**Comment by ace0625** [comment]
lgtm

**Comment by ochanje210** [comment]
@lyw0149 awesome. thanks for letting me know

**Pull request merged**
