### PR TITLE
adding some important stuff

### PR DESCRIPTION
**Pull request by ochanje210**

### CODE REVIEW

**Comment by ethkim** [comment]
Has je joined the team officially? Maintainers are only given out to TLs so even if he has, I can't approve this. :(

**Comment by ochanje210** [comment]
Noooooooi

**Comment by ochanje210** [comment]
Mcgill is the best in the world way above UofT

**Comment by ethkim** [comment]
Please be mindful on leaving comments or sending out PRs for fun. This
isn't meant to be a chat box and all the activity will send out emails to
everyone on the team.

Just want to make sure we don't waste everyone's time. Thanks.

**Comment by ochanje210** [comment]
@ethkim I appreciate your comment and I apologize for my previous behavior. I will keep that in mind!

**Pull request closed without merging**
